cuda_config:
  cudnn_deterministic: True
  cudnn_benchmark: True
  cuda_visible_devices: "1"
  world_size: 1

model_param:
  img_size: 32
  patch_size: 8
  num_classes: 10
  embed_dim: 384
  depth: 6
  num_heads: 8
  
optim:
  optim_name: Adam
  optim_param:
    lr: 0.001
    weight_decay: 0.01

scheduler:
  # scheduler_name: MultiStepLR
  # scheduler_param:
  #   milestones: [10, 30]
  #   gamma: 0.1
  scheduler_name: CosineAnnealingLR
  scheduler_param:
    T_max: 500

use_warmup: False
warmup_param:
  multiplier: 1
  total_epoch: 3

epochs: 500
batch_size: 128
num_workers: 2
log_freq: 15
# log_img_epoch: 100
save_epoch: 20
amp: False
