cuda_config:
  cudnn_deterministic: True
  cudnn_benchmark: True
  cuda_visible_devices: "0"
  world_size: 1

optim:
  optim_name: Adam
  optim_param:
    lr: 0.001

scheduler:
  scheduler_name: MultiStepLR
  scheduler_param:
    milestones: [10, 30]
    gamma: 0.1

warmup_param:
  multiplier: 1
  total_epoch: 1

epochs: 50
batch_size: 64
num_workers: 8
log_freq: 20
log_img_epoch: 100
save_epoch: 100
amp: False


