cuda_config:
  cudnn_deterministic: True
  cudnn_benchmark: True
  cuda_visible_devices: "0, 1"
  world_size: 2

model_param:
  image_size: 32
  patch_size: 4
  num_classes: 10
  dim: 512
  depth: 6
  heads: 8
  mlp_dim: 512
  dropout: 0.1
  emb_dropout: 0.1

optim:
  optim_name: Adam
  optim_param:
    lr: 0.0001

scheduler:
  # scheduler_name: MultiStepLR
  # scheduler_param:
  #   milestones: [10, 30]
  #   gamma: 0.1
  scheduler_name: CosineAnnealingLR
  scheduler_param:
    T_max: 500

use_warmup: False
warmup_param:
  multiplier: 1
  total_epoch: 1

epochs: 500
batch_size: 512
num_workers: 8
log_freq: 5
# log_img_epoch: 100
save_epoch: 20
eval_epoch: 20
amp: False
